#!/bin/bash
set -euo pipefail

# =============================================================================
# MoaV dnstt-ssh server entrypoint
# OpenSSH server for SSH -D SOCKS5 and administrative access through DNS tunnel
# =============================================================================

echo "========================================================"
echo "  MoaV dnstt-ssh (SSH over DNS tunnel)"
echo "========================================================"

# Load public key(s) from state (generated by bootstrap) or env var
PUBKEY_FILE="/state/keys/dnstt-ssh-authorized_keys"

if [[ -n "${DNSTT_SSH_PUBKEY:-}" ]]; then
    echo "[dnstt-ssh] Loading public key from DNSTT_SSH_PUBKEY env var"
    echo "$DNSTT_SSH_PUBKEY" > /home/tunnel/.ssh/authorized_keys
elif [[ -f "$PUBKEY_FILE" ]]; then
    echo "[dnstt-ssh] Loading public key from $PUBKEY_FILE"
    cp "$PUBKEY_FILE" /home/tunnel/.ssh/authorized_keys
else
    echo "[dnstt-ssh] WARNING: No authorized_keys found!"
    echo "[dnstt-ssh] Set DNSTT_SSH_PUBKEY in .env or run bootstrap to generate one."
    echo "[dnstt-ssh] Starting anyway — connections will be refused until a key is added."
    touch /home/tunnel/.ssh/authorized_keys
fi

chmod 600 /home/tunnel/.ssh/authorized_keys
chown tunnel:tunnel /home/tunnel/.ssh/authorized_keys

echo "[dnstt-ssh] SSH server starting on port 2222"
echo "[dnstt-ssh] Authorized keys: $(wc -l < /home/tunnel/.ssh/authorized_keys) key(s)"
echo "[dnstt-ssh] Username: tunnel"
echo ""
echo "[dnstt-ssh] Client usage (SOCKS5 over SSH):"
echo "  ssh -N -D 1080 -p 2222 tunnel@127.0.0.1"

exec /usr/sbin/sshd -D -e -p 2222
