#!/bin/sh
set -e

# =============================================================================
# dnstt server entrypoint
# =============================================================================

# Source config file if it exists (generated by bootstrap)
if [ -f /etc/dnstt/server.conf ]; then
    echo "[dnstt] Loading config from /etc/dnstt/server.conf"
    . /etc/dnstt/server.conf
fi

# Environment variables override config file
if [[ -z "${DNSTT_DOMAIN:-}" ]]; then
    echo "[dnstt] ERROR: DNSTT_DOMAIN is not set!"
    echo "[dnstt] Set DOMAIN in .env or provide DNSTT_DOMAIN directly"
    exit 1
fi
DNSTT_LISTEN="${DNSTT_LISTEN:-:5353}"
# Upstream points to sing-box's mixed inbound (SOCKS5/HTTP proxy on Docker network)
DNSTT_UPSTREAM="${DNSTT_UPSTREAM:-sing-box:1080}"

echo "[dnstt] Starting dnstt-server"
echo "[dnstt] Domain: $DNSTT_DOMAIN"
echo "[dnstt] Listen: $DNSTT_LISTEN"
echo "[dnstt] Upstream: $DNSTT_UPSTREAM"

# NoizDNS MTU — lower values reduce the chance of fragmented DNS responses
# being dropped by restrictive networks.  1232 is the NoizDNS project default
# and works well on most Iranian ISPs.  Adjust via DNSTT_MTU env var.
DNSTT_MTU="${DNSTT_MTU:-1232}"
echo "[dnstt] MTU: $DNSTT_MTU"
echo "[dnstt] Note: binary auto-detects standard dnstt AND NoizDNS (DPI-evasion) clients"

# Look for key file in multiple formats (for backwards compatibility)
KEY_HEX="/state/keys/dnstt-server.key.hex"
KEY_B64="/state/keys/dnstt-server.key.b64"

echo "[dnstt] Looking for key files..."
ls -la /state/keys/ 2>&1 || echo "[dnstt] /state/keys directory does not exist"

# Wait for any key file to appear
timeout=60
elapsed=0
while [ ! -f "$KEY_HEX" ] && [ ! -f "$KEY_B64" ]; do
    echo "[dnstt] Waiting for key file..."
    sleep 2
    elapsed=$((elapsed + 2))
    if [ $elapsed -ge $timeout ]; then
        echo "[dnstt] ERROR: No key file found after ${timeout}s. Run bootstrap first."
        echo "[dnstt] Expected: $KEY_HEX or $KEY_B64"
        ls -la /state/keys/ 2>&1 || true
        exit 1
    fi
done

# Load key - prefer hex, fall back to base64 and convert
if [ -f "$KEY_HEX" ]; then
    echo "[dnstt] Using hex key file: $KEY_HEX"
    PRIVKEY=$(cat "$KEY_HEX" | tr -d '\n\r ')
elif [ -f "$KEY_B64" ]; then
    echo "[dnstt] Using base64 key file: $KEY_B64 (converting to hex)"
    # Convert base64 to hex
    PRIVKEY=$(cat "$KEY_B64" | base64 -d | od -A n -t x1 | tr -d ' \n')
else
    echo "[dnstt] ERROR: No valid key file found"
    exit 1
fi

echo "[dnstt] Private key loaded (${#PRIVKEY} chars)"

# Validate key length (should be 64 hex chars = 32 bytes)
if [ ${#PRIVKEY} -ne 64 ]; then
    echo "[dnstt] WARNING: Key length is ${#PRIVKEY}, expected 64 hex chars"
fi

# Build argument list — optionally add TCP listener for port 853 (often permitted
# through firewalls as "DNS over TLS" traffic, used alongside UDP/5353)
DNSTT_ARGS="-udp $DNSTT_LISTEN -mtu $DNSTT_MTU"

if [ "${DNSTT_ENABLE_TCP:-false}" = "true" ]; then
    DNSTT_TCP_LISTEN="${DNSTT_TCP_LISTEN:-:853}"
    DNSTT_ARGS="$DNSTT_ARGS -tcp $DNSTT_TCP_LISTEN"
    echo "[dnstt] TCP listener enabled on $DNSTT_TCP_LISTEN"
fi

echo "[dnstt] Args: $DNSTT_ARGS $DNSTT_DOMAIN $DNSTT_UPSTREAM"

# shellcheck disable=SC2086
exec dnstt-server $DNSTT_ARGS -privkey "$PRIVKEY" "$DNSTT_DOMAIN" "$DNSTT_UPSTREAM"
