#!/bin/bash
set -euo pipefail

# =============================================================================
# MoaV Knocker server entrypoint
# HMAC-based connection admission proxy — admits valid tokens, deflects probes
# =============================================================================

echo "========================================================"
echo "  MoaV Knocker (DPI evasion + connection admission)"
echo "========================================================"

KNOCKER_LISTEN="${KNOCKER_LISTEN:-:8444}"
KNOCKER_UPSTREAM="${KNOCKER_UPSTREAM:-sing-box:1080}"
KNOCKER_DECOY="${KNOCKER_DECOY:-decoy:80}"

# Load secret from file (generated by bootstrap) or env var
SECRET_FILE="/state/keys/knocker.secret"
if [[ -z "${KNOCKER_SECRET:-}" ]]; then
    # Wait for key to be generated by bootstrap
    timeout=60
    elapsed=0
    while [[ ! -f "$SECRET_FILE" ]]; do
        echo "[knocker] Waiting for secret file $SECRET_FILE ..."
        sleep 2
        elapsed=$((elapsed + 2))
        if [[ $elapsed -ge $timeout ]]; then
            echo "[knocker] ERROR: Secret file not found after ${timeout}s. Run bootstrap first."
            exit 1
        fi
    done
    export KNOCKER_SECRET
    KNOCKER_SECRET=$(cat "$SECRET_FILE" | tr -d '\n\r ')
fi

echo "[knocker] Listen   : $KNOCKER_LISTEN"
echo "[knocker] Upstream : $KNOCKER_UPSTREAM"
echo "[knocker] Decoy    : $KNOCKER_DECOY"
echo "[knocker] Secret   : loaded (${#KNOCKER_SECRET} chars)"

export KNOCKER_LISTEN KNOCKER_UPSTREAM KNOCKER_DECOY KNOCKER_SECRET

exec knocker
