#!/bin/bash
set -euo pipefail

# =============================================================================
# NaiveProxy (Caddy forwardproxy) entrypoint
# NaiveProxy makes HTTPS proxy traffic look indistinguishable from normal
# HTTPS browsing, with Chrome-authentic TLS fingerprints.
# =============================================================================

NAIVE_DOMAIN="${NAIVE_DOMAIN:-${DOMAIN:-localhost}}"
NAIVE_USER="${NAIVE_USER:-naive}"
NAIVE_PASSWORD="${NAIVE_PASS:-}"
NAIVE_LISTEN_PORT="${NAIVE_PORT:-443}"
CERT_DIR="/certs/live/${NAIVE_DOMAIN}"

echo "[naive] NaiveProxy entrypoint starting"
echo "[naive] Domain:    $NAIVE_DOMAIN"
echo "[naive] Port:      $NAIVE_LISTEN_PORT"
echo "[naive] User:      $NAIVE_USER"

if [[ -z "$NAIVE_PASSWORD" ]]; then
    echo "[naive] ERROR: NAIVE_PASS is not set"
    exit 1
fi

# Wait for TLS certificate (generated by certbot or bootstrap)
CERT_FILE="$CERT_DIR/fullchain.pem"
KEY_FILE="$CERT_DIR/privkey.pem"

echo "[naive] Waiting for TLS certificate at $CERT_FILE ..."
timeout=120
elapsed=0
while [[ ! -f "$CERT_FILE" ]] || [[ ! -f "$KEY_FILE" ]]; do
    sleep 3
    elapsed=$((elapsed + 3))
    if [[ $elapsed -ge $timeout ]]; then
        echo "[naive] ERROR: TLS certificate not found after ${timeout}s"
        echo "[naive] Expected: $CERT_FILE"
        ls "$CERT_DIR" 2>/dev/null || echo "[naive] Certificate dir does not exist"
        exit 1
    fi
done

echo "[naive] TLS certificate found"

# Write Caddyfile
CADDYFILE="/tmp/naive-Caddyfile"
cat > "$CADDYFILE" <<EOF
{
    # Global options
    admin off
    log {
        output stderr
        level INFO
        format console
    }
}

:${NAIVE_LISTEN_PORT} {
    tls ${CERT_FILE} ${KEY_FILE}

    route {
        forward_proxy {
            basic_auth ${NAIVE_USER} ${NAIVE_PASSWORD}
            hide_ip
            hide_via
        }
        # Decoy fallback: non-proxy requests see the decoy site
        reverse_proxy http://decoy:80
    }
}
EOF

echo "[naive] Starting Caddy NaiveProxy on :${NAIVE_LISTEN_PORT} ..."
exec caddy run --config "$CADDYFILE" --adapter caddyfile
