#!/bin/bash
set -euo pipefail

# =============================================================================
# Slipstream server entrypoint
# QUIC-over-DNS tunnel - faster alternative to dnstt
# =============================================================================

echo "================================================"
echo "  MoaV Slipstream (QUIC-over-DNS)"
echo "================================================"

SLIPSTREAM_DOMAIN="${SLIPSTREAM_DOMAIN:-}"
SLIPSTREAM_LISTEN_HOST="${SLIPSTREAM_LISTEN_HOST:-0.0.0.0}"
SLIPSTREAM_LISTEN_PORT="${SLIPSTREAM_LISTEN_PORT:-5354}"
SLIPSTREAM_UPSTREAM="${SLIPSTREAM_UPSTREAM:-sing-box:1080}"

CERT_FILE="/state/keys/slipstream-cert.pem"
KEY_FILE="/state/keys/slipstream-key.pem"

if [[ -z "$SLIPSTREAM_DOMAIN" ]]; then
    echo "[slipstream] ERROR: SLIPSTREAM_DOMAIN is not set!"
    echo "[slipstream] Set DOMAIN and SLIPSTREAM_SUBDOMAIN in .env"
    exit 1
fi

echo "[slipstream] Domain: $SLIPSTREAM_DOMAIN"
echo "[slipstream] Listen: $SLIPSTREAM_LISTEN_HOST:$SLIPSTREAM_LISTEN_PORT"
echo "[slipstream] Upstream: $SLIPSTREAM_UPSTREAM"

# Wait for certificate files (generated by bootstrap)
echo "[slipstream] Looking for certificate files..."
timeout=60
elapsed=0
while [[ ! -f "$CERT_FILE" ]] || [[ ! -f "$KEY_FILE" ]]; do
    echo "[slipstream] Waiting for cert/key files..."
    sleep 2
    elapsed=$((elapsed + 2))
    if [[ $elapsed -ge $timeout ]]; then
        echo "[slipstream] ERROR: Certificate files not found after ${timeout}s. Run bootstrap first."
        echo "[slipstream] Expected: $CERT_FILE and $KEY_FILE"
        ls -la /state/keys/ 2>&1 || true
        exit 1
    fi
done

echo "[slipstream] Certificate loaded: $CERT_FILE"
echo "================================================"

exec slipstream-server \
    --dns-listen-host "$SLIPSTREAM_LISTEN_HOST" \
    --dns-listen-port "$SLIPSTREAM_LISTEN_PORT" \
    --domain "$SLIPSTREAM_DOMAIN" \
    --target-address "$SLIPSTREAM_UPSTREAM" \
    --cert "$CERT_FILE" \
    --key "$KEY_FILE"
